apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql-wordpress-rs
  labels:
    app: mysql-wordpress-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs-secret
  template:
    metadata:
      labels:
        app: mysql-rs-secret
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: wordpress-local-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: wordpress-local-storage
          persistentVolumeClaim:
            claimName: wordpress-mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql
  labels:
    name: mysql-wordpress-rs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi